#!/bin/sh
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

remaps &			# switch caps/esc etc.
picom &
dwmblocks 2>&1 >/dev/null &	# dwmstatus statusbar
dunst &				# dunst for notifications
xset r rate 300 50 &		# Speed xrate up
unclutter &			# Remove mouse when idle
mpd-module-update &		# Check for when to update the mpd module
setbg ~/Images/backgrounds
[ -x $(command -v wal) ] && wal --theme $(cat ~/.local/share/walpicks.txt | shuf -n1) &> ~/waldo.log
