#!/bin/sh
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
remaps &
~/.local/bin/statusbar/bar.sh &
dunst &
xset r rate 300 50 &
unclutter &
mpd-module-update &
xinput disable 'SynPS/2 Synaptics TouchPad' & # use mouse or trackpoint only
picom --no-vsync --no-use-damage & # composite manager
[[ -x VBoxClient-all ]] && VBoxClient-all 2> ~/vbox.log &
[[ -x ~/.screenlayout/default.sh ]] && ~/.screenlayout/default.sh &
[[ -x $(command setbg) ]] && setbg &
